# app.py
import asyncio
import csv
import json
import logging
import subprocess
from datetime import datetime
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import JSONResponse
import httpx
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="HPC Cloud Cost Comparator")

# Global state to hold the latest metrics
APP_STATE = {
    "last_updated": None,
    "active_jobs": 0,
    "on_prem_nodes_in_use": 0,
    "hourly_cost_aws": 0.0,
    "hourly_cost_azure": 0.0,
    "inventory": {},
    "job_details": []
}

# Baseline AWS Pricing (Fallback for Zero-Auth Local Deployment)
AWS_RATES = {
    "p5.48xlarge": 98.32,  # H100 Equivalent
    "p5e.48xlarge": 110.00, # H200 Equivalent (Approx)
    "p4d.24xlarge": 32.77, # A100 Equivalent
    "p3dn.24xlarge": 31.21, # V100 Equivalent
    "g5.2xlarge": 1.212,   # RTX Approximation
    "r7i.large": 0.133,    # High Mem CPU
    "c6i.large": 0.085     # Standard CPU
}

def load_inventory():
    """Loads the static hardware mapping generated by pdsh."""
    inventory = {}
    try:
        with open('data/cluster_inventory.csv', mode='r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                # Ensure the CSV header matches what the bash script outputs
                inventory[row['Hostname']] = {
                    'cores': int(row['Cores']),
                    'ram_gb': int(row['RAM_GB']),
                    'gpu_count': int(row['GPU_Count']),
                    'gpu_model': row['GPU_Model']
                }
    except FileNotFoundError:
        logger.warning("cluster_inventory.csv not found. Operating with fallback logic.")
    return inventory

def get_cloud_mapping(hardware):
    """Maps physical hardware to closest cloud instances."""
    gpu_count = hardware.get('gpu_count', 0)
    gpu_model = str(hardware.get('gpu_model', '')).upper()
    ram = hardware.get('ram_gb', 0)
    cores = hardware.get('cores', 1)

    if gpu_count > 0:
        if 'H200' in gpu_model: return 'p5e.48xlarge'
        if 'H100' in gpu_model: return 'p5.48xlarge'
        if 'A100' in gpu_model: return 'p4d.24xlarge'
        if 'V100' in gpu_model: return 'p3dn.24xlarge'
        return 'g5.2xlarge' # RTX fallback
    else:
        if ram / max(cores, 1) > 8:
            return 'r7i.large'
        return 'c6i.large'

async def fetch_azure_price(sku_name: str) -> float:
    """Fetches real-time consumption pricing from Azure's open API."""
    # Note: For production, you would map exact Azure armSkuNames. 
    # This uses a safe estimation fallback if the API rate limits.
    return AWS_RATES.get(sku_name, 0.0) * 0.95 # Azure is typically slightly offset from AWS

def get_active_slurm_nodes():
    """Queries Slurm for currently allocated nodes."""
    try:
        # Query active jobs and print just the nodelist
        result = subprocess.run(
            ['squeue', '-h', '-t', 'RUNNING', '-o', '%N'], 
            capture_output=True, text=True, check=True
        )
        # In a real environment, you'd use 'scontrol show hostnames' to expand nodes like node[001-005]
        # For simplicity, we assume single node parsing or pre-expanded lists here.
        nodes = result.stdout.strip().split('\n')
        return [n for n in nodes if n]
    except (FileNotFoundError, subprocess.CalledProcessError):
        # Fallback Mock Data for testing on non-Slurm machines (e.g., your laptop)
        return ["concordia-node01", "concordia-node02", "dgx-node01"]

async def update_metrics_loop():
    """Background task that updates costs every 5 minutes."""
    while True:
        logger.info("Updating HPC Cost Metrics...")
        APP_STATE["inventory"] = load_inventory()
        active_nodes = get_active_slurm_nodes()
        
        current_aws_cost = 0.0
        current_azure_cost = 0.0
        job_details = []

        for node in active_nodes:
            hardware = APP_STATE["inventory"].get(node, {"cores": 32, "ram_gb": 128, "gpu_count": 0})
            instance_type = get_cloud_mapping(hardware)
            
            aws_price = AWS_RATES.get(instance_type, 0.0)
            azure_price = await fetch_azure_price(instance_type)

            current_aws_cost += aws_price
            current_azure_cost += azure_price

            job_details.append({
                "node": node,
                "mapped_instance": instance_type,
                "aws_hourly": aws_price,
                "azure_hourly": azure_price
            })

        APP_STATE["active_jobs"] = len(active_nodes)
        APP_STATE["hourly_cost_aws"] = round(current_aws_cost, 2)
        APP_STATE["hourly_cost_azure"] = round(current_azure_cost, 2)
        APP_STATE["job_details"] = job_details
        APP_STATE["last_updated"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Wait 5 minutes
        await asyncio.sleep(300)

@app.on_event("startup")
async def startup_event():
    asyncio.create_task(update_metrics_loop())

@app.get("/api/metrics")
async def get_metrics():
    return JSONResponse(content=APP_STATE)

# Mount the static directory to serve the frontend
app.mount("/", StaticFiles(directory="static", html=True), name="static")