# app.py
import asyncio
import csv
import json
import logging
from datetime import datetime, timedelta
from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from typing import List

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="HPC Cloud Cost Comparator")

# --- Pydantic Models for API Data ---
class AgentPayload(BaseModel):
    cluster_name: str
    active_nodes: List[str]
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

# --- Global State Management ---
# The state now holds data per cluster and tracks agent heartbeats.
APP_STATE = {
    "last_updated": None,
    "clusters": {}, # e.g., {"cluster-a": {"active_nodes": [], "last_seen": ...}}
    "inventory": {},
    # Aggregated metrics will be calculated from the "clusters" dict
    "total_active_jobs": 0,
    "hourly_cost_aws": 0.0,
    "hourly_cost_azure": 0.0,
    "job_details": []
}
AGENT_TIMEOUT_MINUTES = 10

# Baseline AWS Pricing (Fallback for Zero-Auth Local Deployment)
AWS_RATES = {
    "p5.48xlarge": 98.32,  # H100 Equivalent
    "p5e.48xlarge": 110.00, # H200 Equivalent (Approx)
    "p4d.24xlarge": 32.77, # A100 Equivalent
    "p3dn.24xlarge": 31.21, # V100 Equivalent
    "g5.2xlarge": 1.212,   # RTX Approximation
    "r7i.large": 0.133,    # High Mem CPU
    "c6i.large": 0.085     # Standard CPU
}

def load_inventory():
    """Loads the static hardware mapping generated by pdsh."""
    inventory = {}
    try:
        with open('data/cluster_inventory.csv', mode='r') as file:
            reader = csv.DictReader(file)
            for row in reader:
                # Ensure the CSV header matches what the bash script outputs
                inventory[row['Hostname']] = {
                    'cores': int(row['Cores']),
                    'ram_gb': int(row['RAM_GB']),
                    'gpu_count': int(row['GPU_Count']),
                    'gpu_model': row['GPU_Model']
                }
    except FileNotFoundError:
        logger.warning("cluster_inventory.csv not found. Operating with fallback logic.")
    return inventory

def get_cloud_mapping(hardware):
    """Maps physical hardware to closest cloud instances."""
    gpu_count = hardware.get('gpu_count', 0)
    gpu_model = str(hardware.get('gpu_model', '')).upper()
    ram = hardware.get('ram_gb', 0)
    cores = hardware.get('cores', 1)

    if gpu_count > 0:
        if 'H200' in gpu_model: return 'p5e.48xlarge'
        if 'H100' in gpu_model: return 'p5.48xlarge'
        if 'A100' in gpu_model: return 'p4d.24xlarge'
        if 'V100' in gpu_model: return 'p3dn.24xlarge'
        return 'g5.2xlarge' # RTX fallback
    else:
        if ram / max(cores, 1) > 8:
            return 'r7i.large'
        return 'c6i.large'

async def fetch_azure_price(sku_name: str) -> float:
    """Fetches real-time consumption pricing from Azure's open API."""
    # Note: For production, you would map exact Azure armSkuNames.
    # This uses a safe estimation fallback if the API rate limits.
    return AWS_RATES.get(sku_name, 0.0) * 0.95 # Azure is typically slightly offset from AWS

# --- New Endpoint to Receive Agent Data ---
@app.post("/api/agent/data")
async def receive_agent_data(payload: AgentPayload):
    """Endpoint for agents to post their Slurm data."""
    logger.info(f"Received data from agent on cluster: {payload.cluster_name}")
    APP_STATE["clusters"][payload.cluster_name] = {
        "active_nodes": payload.active_nodes,
        "last_seen": datetime.utcnow()
    }
    return {"status": "success", "message": f"Data for {payload.cluster_name} received."}


def process_and_aggregate_metrics():
    """
    Processes the collected agent data in APP_STATE to calculate aggregate costs.
    This function replaces the direct Slurm query.
    """
    # Prune stale agents first
    now = datetime.utcnow()
    stale_clusters = [
        name for name, data in APP_STATE["clusters"].items()
        if now - data["last_seen"] > timedelta(minutes=AGENT_TIMEOUT_MINUTES)
    ]
    for name in stale_clusters:
        logger.warning(f"Agent for cluster '{name}' is stale. Removing from metrics.")
        del APP_STATE["clusters"][name]

    # Now, calculate metrics from active agents
    current_aws_cost = 0.0
    current_azure_cost = 0.0
    job_details = []
    total_active_nodes = 0

    for cluster_name, data in APP_STATE["clusters"].items():
        active_nodes = data["active_nodes"]
        logger.info(f"Processing {len(active_nodes)} nodes from cluster '{cluster_name}'.")
        total_active_nodes += len(active_nodes)

        for node in active_nodes:
            hardware = APP_STATE["inventory"].get(node) # Try to get the hardware
            if not hardware:
                logger.warning(f"Node '{node}' from cluster '{cluster_name}' not found in inventory. Using default hardware specs.")
                hardware = {"cores": 32, "ram_gb": 128, "gpu_count": 0} # Fallback
            
            instance_type = get_cloud_mapping(hardware)

            aws_price = AWS_RATES.get(instance_type, 0.0)
            # The original async call is now made sync inside the loop for simplicity
            azure_price = AWS_RATES.get(instance_type, 0.0) * 0.95

            current_aws_cost += aws_price
            current_azure_cost += azure_price

            job_details.append({
                "node": f"{cluster_name}/{node}", # Prefix node with cluster name
                "mapped_instance": instance_type,
                "aws_hourly": aws_price,
                "azure_hourly": azure_price
            })

    APP_STATE["total_active_jobs"] = total_active_nodes
    APP_STATE["hourly_cost_aws"] = round(current_aws_cost, 2)
    APP_STATE["hourly_cost_azure"] = round(current_azure_cost, 2)
    APP_STATE["job_details"] = job_details
    APP_STATE["last_updated"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")


async def update_metrics_loop():
    """Background task that updates costs every 10 seconds based on agent data."""
    # Load inventory once on startup of the loop
    APP_STATE["inventory"] = load_inventory()
    
    while True:
        logger.info("Processing agent data to update HPC Cost Metrics...")
        
        process_and_aggregate_metrics()

        # Wait 10 seconds
        await asyncio.sleep(10)

@app.on_event("startup")
async def startup_event():
    # Load inventory on startup
    APP_STATE["inventory"] = load_inventory()
    # Start the background processing loop
    asyncio.create_task(update_metrics_loop())

@app.get("/api/metrics")
async def get_metrics():
    # The structure returned to the frontend needs to match what it expects
    return JSONResponse(content={
        "active_jobs": APP_STATE["total_active_jobs"],
        "hourly_cost_aws": APP_STATE["hourly_cost_aws"],
        "hourly_cost_azure": APP_STATE["hourly_cost_azure"],
        "job_details": APP_STATE["job_details"],
        "last_updated": APP_STATE["last_updated"],
    })

# Mount the static directory to serve the frontend
app.mount("/", StaticFiles(directory="static", html=True), name="static")
