#!/usr/bin/env python3
"""
import_history.py — Import sacct CSV dump into the Shovly historical SQLite database.

Usage:
    python3 import_history.py [data/sacct_raw.csv] [--db data/historical.db]

The CSV is pipe-delimited with NO header, generated by dump_history.sh:
    JobID|User|Submit|Start|End|ReqCPUS|ReqMem|ReqTRES|ElapsedRaw|TimelimitRaw|State|ClusterName

Costs are calculated using the same instance-matching logic as app.py; keep
the two catalogs in sync if you update instance pricing.
"""

import argparse
import functools
import logging
import os
import sqlite3
import sys
import time as time_module
from datetime import datetime as _datetime

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

BATCH_SIZE = 100_000

# ---------------------------------------------------------------------------
# Instance catalogs — loaded from CSV price lists at startup
# ---------------------------------------------------------------------------
import sys as _sys
_sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "hpc-cost-comparator"))
from load_pricelist import GPU_MODEL_MAP, load_catalogs as _load_catalogs
del _sys

AWS_INSTANCES, AZURE_INSTANCES = _load_catalogs()



# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def parse_mem_mb(mem_str):
    s = mem_str.strip().upper()
    if not s or s in ("N/A", "0", "UNLIMITED"):
        return 0
    try:
        if s.endswith("T"):
            return int(float(s[:-1]) * 1024 * 1024)
        if s.endswith("G"):
            return int(float(s[:-1]) * 1024)
        if s.endswith("M"):
            return int(float(s[:-1]))
        if s.endswith("K"):
            return max(1, int(float(s[:-1]) / 1024))
        return int(s)
    except ValueError:
        return 0


def parse_sacct_mem_mb(mem_str):
    """Parse sacct ReqMem: strip trailing 'n' (per-node) or 'c' (per-cpu) suffix."""
    s = mem_str.strip().upper()
    if not s or s in ("0", "UNLIMITED", "N/A"):
        return 0
    if s.endswith("N") or s.endswith("C"):
        s = s[:-1]
    return parse_mem_mb(s)


def parse_tres_gpu(tres_str):
    """
    Parse GPU info from sacct ReqTRES field.
    Examples: 'billing=1,cpu=8,mem=32G,node=1,gres/gpu=2'  -> (2, '')
              'gres/gpu:a30=1'                               -> (1, 'a30')
    """
    if not tres_str:
        return 0, ""
    for part in tres_str.strip().lower().split(","):
        part = part.strip()
        if "gres/gpu" not in part:
            continue
        if "=" in part:
            key, val = part.rsplit("=", 1)
            try:
                count = int(val)
            except ValueError:
                count = 1
            model = key.split(":", 1)[1] if ":" in key else ""
            return count, model
    return 0, ""


def parse_tres_node_count(tres_str):
    """Extract node count from sacct ReqTRES field. Returns 1 if absent."""
    if not tres_str:
        return 1
    for part in tres_str.strip().lower().split(","):
        part = part.strip()
        if part.startswith("node="):
            try:
                return max(1, int(part.split("=", 1)[1]))
            except ValueError:
                pass
    return 1


def parse_sacct_timestamp(ts_str):
    """Convert sacct timestamp string (YYYY-MM-DDTHH:MM:SS) to Unix timestamp integer."""
    s = ts_str.strip()
    if not s or s.lower() in ("unknown", "none", ""):
        return 0
    try:
        return int(_datetime.fromisoformat(s).timestamp())
    except (ValueError, OverflowError):
        return 0


def parse_nodelist_first(nodelist_str):
    """
    Extract the first node name from a Slurm compressed NodeList string.
    Examples:
      'hpctpa3pc0001'          -> 'hpctpa3pc0001'
      'hpctpa3pc[0001-0005]'   -> 'hpctpa3pc0001'
      'node[01,03-05],gpu01'   -> 'node01'
    """
    import re
    s = nodelist_str.strip()
    if not s or s.lower() in ("n/a", "none", ""):
        return ""
    first = s.split(",")[0].strip()
    m = re.match(r"^([A-Za-z0-9._-]+)\[(\d+)", first)
    return (m.group(1) + m.group(2)) if m else first


# ---------------------------------------------------------------------------
# Instance matching  (keep in sync with app.py:find_best_instance)
# ---------------------------------------------------------------------------

def find_best_instance(catalog, cpus, mem_mb, gpu_count, gpu_model):
    mem_gb = mem_mb / 1024.0
    norm_gpu = GPU_MODEL_MAP.get(gpu_model.lower(), gpu_model.upper()) if gpu_model else ""

    if gpu_count > 0:
        c = [i for i in catalog
             if i["gpu_count"] >= gpu_count
             and (not norm_gpu or i["gpu_model"] == norm_gpu)
             and i["vcpus"] >= max(cpus, 1)
             and i["mem_gb"] >= mem_gb]
        if not c:
            c = [i for i in catalog
                 if i["gpu_count"] >= gpu_count
                 and (not norm_gpu or i["gpu_model"] == norm_gpu)
                 and i["vcpus"] >= max(cpus, 1)]
        # Pass 2.5: relax model but prefer Nvidia over AMD
        if not c:
            c = [i for i in catalog
                 if i["gpu_count"] >= gpu_count
                 and i.get("gpu_vendor", "nvidia") == "nvidia"
                 and i["vcpus"] >= max(cpus, 1)]
        if not c:
            c = [i for i in catalog
                 if i["gpu_count"] >= gpu_count and i["vcpus"] >= max(cpus, 1)]
        if not c:
            c = [i for i in catalog if i["gpu_count"] >= gpu_count]
        if c:
            return min(c, key=lambda x: x["price"])

    c = [i for i in catalog
         if i["gpu_count"] == 0 and i["vcpus"] >= max(cpus, 1) and i["mem_gb"] >= mem_gb]
    if not c:
        c = [i for i in catalog if i["gpu_count"] == 0 and i["vcpus"] >= max(cpus, 1)]
    if not c:
        c = [i for i in catalog if i["gpu_count"] == 0]
    if c:
        return min(c, key=lambda x: x["price"])
    return min(catalog, key=lambda x: x["price"])


@functools.lru_cache(maxsize=8192)
def _aws_instance(cpus, mem_mb, gpu_count, gpu_model):
    """Cached lookup — jobs sharing the same resource profile skip catalog scans."""
    return find_best_instance(AWS_INSTANCES, cpus, mem_mb, gpu_count, gpu_model)


@functools.lru_cache(maxsize=8192)
def _azure_instance(cpus, mem_mb, gpu_count, gpu_model):
    """Cached lookup — jobs sharing the same resource profile skip catalog scans."""
    return find_best_instance(AZURE_INSTANCES, cpus, mem_mb, gpu_count, gpu_model)


def parse_tres_all(tres_str):
    """Parse GPU count, GPU model, and node count from sacct ReqTRES in a single pass."""
    gpu_count, gpu_model, num_nodes = 0, "", 1
    if not tres_str:
        return gpu_count, gpu_model, num_nodes
    for part in tres_str.strip().lower().split(","):
        part = part.strip()
        if part.startswith("node="):
            try:
                num_nodes = max(1, int(part.split("=", 1)[1]))
            except ValueError:
                pass
        elif "gres/gpu" in part and "=" in part:
            key, val = part.rsplit("=", 1)
            try:
                gpu_count = int(val)
            except ValueError:
                gpu_count = 1
            gpu_model = key.split(":", 1)[1] if ":" in key else ""
    return gpu_count, gpu_model, num_nodes


# ---------------------------------------------------------------------------
# SQLite schema
# ---------------------------------------------------------------------------
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS jobs (
    job_id        TEXT,
    cluster       TEXT,
    username      TEXT    NOT NULL,
    start_time    INTEGER,
    end_time      INTEGER,
    req_cpus      INTEGER DEFAULT 1,
    req_mem_mb    INTEGER DEFAULT 0,
    gpu_count     INTEGER DEFAULT 0,
    gpu_model     TEXT    DEFAULT '',
    time_limit_min INTEGER DEFAULT 0,
    elapsed_min   INTEGER DEFAULT 0,
    state         TEXT    DEFAULT '',
    aws_instance  TEXT    DEFAULT '',
    aws_total     REAL    DEFAULT 0.0,
    azure_instance TEXT   DEFAULT '',
    azure_total   REAL    DEFAULT 0.0,
    num_nodes     INTEGER DEFAULT 1,
    PRIMARY KEY (job_id, cluster)
);
CREATE INDEX IF NOT EXISTS idx_start   ON jobs(start_time);
CREATE INDEX IF NOT EXISTS idx_user    ON jobs(username);
CREATE INDEX IF NOT EXISTS idx_cluster ON jobs(cluster);
"""

INSERT_SQL_IGNORE  = "INSERT OR IGNORE  INTO jobs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
INSERT_SQL_REPLACE = "INSERT OR REPLACE INTO jobs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"


def init_db(conn):
    for stmt in SCHEMA_SQL.strip().split(";"):
        stmt = stmt.strip()
        if stmt:
            conn.execute(stmt)
    # Migrate DBs that pre-date the num_nodes column
    try:
        conn.execute("ALTER TABLE jobs ADD COLUMN num_nodes INTEGER DEFAULT 1")
    except Exception:
        pass
    conn.commit()


# ---------------------------------------------------------------------------
# Import logic
# ---------------------------------------------------------------------------

def import_csv(csv_path, db_path, default_gpu_model="", node_gpu_map=None, force_update=False):
    logger.info("Opening database: %s", db_path)
    if force_update:
        logger.info("--force-update: existing records will be REPLACED with recalculated costs.")
    if node_gpu_map:
        logger.info("Node GPU map loaded: %d nodes.", len(node_gpu_map))
    if default_gpu_model:
        logger.info("Default GPU model fallback: %s", default_gpu_model)
    INSERT_SQL = INSERT_SQL_REPLACE if force_update else INSERT_SQL_IGNORE
    os.makedirs(os.path.dirname(os.path.abspath(db_path)), exist_ok=True)
    conn = sqlite3.connect(db_path)
    # Tune SQLite for bulk-import throughput
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=OFF")       # safe for batch import; re-run on crash
    conn.execute("PRAGMA cache_size=-262144")    # 256 MB page cache
    conn.execute("PRAGMA temp_store=MEMORY")
    conn.execute("PRAGMA mmap_size=2147483648")  # 2 GB memory-mapped I/O
    init_db(conn)

    inserted = 0
    skipped  = 0
    batch    = []

    # Pre-load existing job IDs so INSERT OR IGNORE rows can be skipped before
    # expensive TRES parsing and find_best_instance catalog scans.
    existing_ids: set = set()
    if not force_update:
        logger.info("Pre-loading existing job IDs (may take a moment for large DBs)...")
        existing_ids = set(row[0] for row in conn.execute("SELECT job_id FROM jobs"))
        logger.info("  %d existing records found — will skip on re-import.", len(existing_ids))

    logger.info("Reading: %s", csv_path)
    with open(csv_path, "r") as fh:
        for line_num, line in enumerate(fh, 1):
            parts = line.rstrip("\n").split("|")
            # Support both legacy 12-column (no NodeList) and new 13-column format
            if len(parts) == 13:
                # New format: 12 sacct fields + ClusterName
                nodelist_str = parts[11].strip()
                cluster      = parts[12].strip() or "unknown"
            elif len(parts) == 12:
                # Legacy format: 11 sacct fields + ClusterName (no NodeList)
                nodelist_str = ""
                cluster      = parts[11].strip() or "unknown"
            else:
                skipped += 1
                continue

            job_id = parts[0].strip()
            if "." in job_id:
                skipped += 1
                continue  # Skip job steps (e.g. 12345.batch)

            # Skip already-imported rows before any expensive work
            if existing_ids and job_id in existing_ids:
                skipped += 1
                continue

            username = parts[1].strip()
            start_ts = parse_sacct_timestamp(parts[3])
            if start_ts == 0:
                skipped += 1
                continue  # Skip jobs that never started

            try:
                req_cpus = int(parts[5].strip())
            except ValueError:
                req_cpus = 1

            try:
                elapsed_sec = int(parts[8].strip())
                elapsed_min = elapsed_sec // 60
            except ValueError:
                elapsed_min = 0

            try:
                time_limit_min = int(parts[9].strip())
            except ValueError:
                time_limit_min = 0

            gpu_count, gpu_model, num_nodes = parse_tres_all(parts[7])
            # GPU model resolution priority:
            #   1. Parsed directly from ReqTRES (most accurate)
            #   2. Node map lookup via NodeList (from scontrol show nodes)
            #   3. --default-gpu-model CLI fallback
            if gpu_count > 0 and not gpu_model:
                if nodelist_str and node_gpu_map:
                    first_node = parse_nodelist_first(nodelist_str)
                    gpu_model  = node_gpu_map.get(first_node, "")
                if not gpu_model and default_gpu_model:
                    gpu_model = default_gpu_model
            req_mem_mb = parse_sacct_mem_mb(parts[6])

            # Normalize to per-node resources for cloud instance matching
            if num_nodes > 1:
                req_cpus  = max(1, req_cpus  // num_nodes)
                gpu_count = max(1, gpu_count // num_nodes)

            aws_inst   = _aws_instance(req_cpus, req_mem_mb, gpu_count, gpu_model)
            azure_inst = _azure_instance(req_cpus, req_mem_mb, gpu_count, gpu_model)

            # Use time_limit if available, otherwise fall back to elapsed
            time_hours = (time_limit_min or elapsed_min) / 60.0
            aws_total   = round(aws_inst["price"]   * time_hours * num_nodes, 4)
            azure_total = round(azure_inst["price"] * time_hours * num_nodes, 4)

            batch.append((
                job_id, cluster, username,
                start_ts, parse_sacct_timestamp(parts[4]),
                req_cpus, req_mem_mb,
                gpu_count, gpu_model,
                time_limit_min, elapsed_min,
                parts[10].strip(),
                aws_inst["name"],   aws_total,
                azure_inst["name"], azure_total,
                num_nodes,
            ))

            if len(batch) >= BATCH_SIZE:
                conn.executemany(INSERT_SQL, batch)
                conn.commit()
                inserted += len(batch)
                logger.info("  Inserted %d records (line %d)...", inserted, line_num)
                batch = []

    if batch:
        conn.executemany(INSERT_SQL, batch)
        conn.commit()
        inserted += len(batch)

    conn.close()
    logger.info("Import complete.  Inserted: %d  |  Skipped: %d", inserted, skipped)
    aws_ci, azure_ci = _aws_instance.cache_info(), _azure_instance.cache_info()
    logger.info("AWS   cache: hits=%-8d misses=%-6d  hit rate=%.1f%%",
                aws_ci.hits, aws_ci.misses,
                100 * aws_ci.hits / max(1, aws_ci.hits + aws_ci.misses))
    logger.info("Azure cache: hits=%-8d misses=%-6d  hit rate=%.1f%%",
                azure_ci.hits, azure_ci.misses,
                100 * azure_ci.hits / max(1, azure_ci.hits + azure_ci.misses))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Import sacct CSV dump into the Shovly historical SQLite database."
    )
    parser.add_argument(
        "csv_file", nargs="?", default="data/sacct_raw.csv",
        help="Path to the sacct pipe-delimited CSV (default: data/sacct_raw.csv)"
    )
    parser.add_argument(
        "--db", default="data/historical.db",
        help="Path to the SQLite database file (default: data/historical.db)"
    )
    parser.add_argument(
        "--default-gpu-model", default="", metavar="MODEL",
        help="GPU model fallback when ReqTRES and node map both lack model info "
             "(e.g. 'a30')."
    )
    parser.add_argument(
        "--node-gpu-map", default="", metavar="PATH",
        help="Path to node GPU map CSV generated by dump_history.sh "
             "(format: node_name|gpu_model, one per line). Used to resolve "
             "GPU model for jobs submitted without an explicit model in --gres."
    )
    parser.add_argument(
        "--force-update", action="store_true",
        help="Replace existing DB records instead of skipping them (INSERT OR REPLACE). "
             "Use this when re-importing after fixing GPU detection so that historical "
             "costs are recalculated with correct GPU instance pricing."
    )
    args = parser.parse_args()

    if not os.path.exists(args.csv_file):
        logger.error("CSV file not found: %s", args.csv_file)
        sys.exit(1)

    # Load node GPU map if provided
    node_gpu_map = {}
    if args.node_gpu_map:
        if not os.path.exists(args.node_gpu_map):
            logger.warning("Node GPU map file not found: %s — skipping.", args.node_gpu_map)
        else:
            with open(args.node_gpu_map, "r") as fh:
                for line in fh:
                    cols = line.strip().split("|")
                    if len(cols) == 2 and cols[0] and cols[1]:
                        node_gpu_map[cols[0].strip()] = cols[1].strip().lower()
            logger.info("Loaded node GPU map: %d nodes from %s.", len(node_gpu_map), args.node_gpu_map)

    import_csv(args.csv_file, args.db,
               default_gpu_model=args.default_gpu_model,
               node_gpu_map=node_gpu_map,
               force_update=args.force_update)


if __name__ == "__main__":
    main()
