#!/usr/bin/env python3
"""
import_history.py — Import sacct CSV dump into the Shovly historical SQLite database.

Usage:
    python3 import_history.py [data/sacct_raw.csv] [--db data/historical.db]

The CSV is pipe-delimited with NO header, generated by dump_history.sh:
    JobID|User|Submit|Start|End|ReqCPUS|ReqMem|ReqTRES|ElapsedRaw|TimelimitRaw|State|ClusterName

Costs are calculated using the same instance-matching logic as app.py; keep
the two catalogs in sync if you update instance pricing.
"""

import argparse
import logging
import os
import sqlite3
import sys
import time as time_module

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

BATCH_SIZE = 10_000

# ---------------------------------------------------------------------------
# GPU model normalisation map  (keep in sync with app.py)
# ---------------------------------------------------------------------------
GPU_MODEL_MAP = {
    "h100": "H100", "h200": "H200",
    "a100": "A100",
    "a30":  "A10G", "a10g": "A10G", "a10": "A10G",
    "v100": "V100",
    "t4":   "T4",
    "l40":  "L40S", "l40s": "L40S",
}

# ---------------------------------------------------------------------------
# AWS instance catalog  (keep in sync with app.py)
# ---------------------------------------------------------------------------
AWS_INSTANCES = [
    # H100
    {"name": "p5.48xlarge",    "vcpus": 192, "mem_gb": 2048, "gpu_count": 8, "gpu_model": "H100",  "price": 98.32},
    # A100
    {"name": "p4d.24xlarge",   "vcpus": 96,  "mem_gb": 1152, "gpu_count": 8, "gpu_model": "A100",  "price": 32.77},
    {"name": "p4de.24xlarge",  "vcpus": 96,  "mem_gb": 1152, "gpu_count": 8, "gpu_model": "A100",  "price": 40.96},
    # V100
    {"name": "p3.2xlarge",     "vcpus": 8,   "mem_gb": 61,   "gpu_count": 1, "gpu_model": "V100",  "price": 3.06},
    {"name": "p3.8xlarge",     "vcpus": 32,  "mem_gb": 244,  "gpu_count": 4, "gpu_model": "V100",  "price": 12.24},
    {"name": "p3.16xlarge",    "vcpus": 64,  "mem_gb": 488,  "gpu_count": 8, "gpu_model": "V100",  "price": 24.48},
    {"name": "p3dn.24xlarge",  "vcpus": 96,  "mem_gb": 768,  "gpu_count": 8, "gpu_model": "V100",  "price": 31.21},
    # A10G
    {"name": "g5.xlarge",      "vcpus": 4,   "mem_gb": 16,   "gpu_count": 1, "gpu_model": "A10G",  "price": 1.006},
    {"name": "g5.2xlarge",     "vcpus": 8,   "mem_gb": 32,   "gpu_count": 1, "gpu_model": "A10G",  "price": 1.212},
    {"name": "g5.4xlarge",     "vcpus": 16,  "mem_gb": 64,   "gpu_count": 1, "gpu_model": "A10G",  "price": 1.624},
    {"name": "g5.8xlarge",     "vcpus": 32,  "mem_gb": 128,  "gpu_count": 1, "gpu_model": "A10G",  "price": 2.448},
    {"name": "g5.12xlarge",    "vcpus": 48,  "mem_gb": 192,  "gpu_count": 4, "gpu_model": "A10G",  "price": 5.672},
    {"name": "g5.16xlarge",    "vcpus": 64,  "mem_gb": 256,  "gpu_count": 1, "gpu_model": "A10G",  "price": 4.096},
    {"name": "g5.24xlarge",    "vcpus": 96,  "mem_gb": 384,  "gpu_count": 4, "gpu_model": "A10G",  "price": 8.144},
    {"name": "g5.48xlarge",    "vcpus": 192, "mem_gb": 768,  "gpu_count": 8, "gpu_model": "A10G",  "price": 16.288},
    # T4
    {"name": "g4dn.xlarge",    "vcpus": 4,   "mem_gb": 16,   "gpu_count": 1, "gpu_model": "T4",    "price": 0.526},
    {"name": "g4dn.2xlarge",   "vcpus": 8,   "mem_gb": 32,   "gpu_count": 1, "gpu_model": "T4",    "price": 0.752},
    {"name": "g4dn.4xlarge",   "vcpus": 16,  "mem_gb": 64,   "gpu_count": 1, "gpu_model": "T4",    "price": 1.204},
    {"name": "g4dn.8xlarge",   "vcpus": 32,  "mem_gb": 128,  "gpu_count": 1, "gpu_model": "T4",    "price": 2.264},
    {"name": "g4dn.12xlarge",  "vcpus": 48,  "mem_gb": 192,  "gpu_count": 4, "gpu_model": "T4",    "price": 3.912},
    {"name": "g4dn.16xlarge",  "vcpus": 64,  "mem_gb": 256,  "gpu_count": 1, "gpu_model": "T4",    "price": 4.528},
    # Compute optimised
    {"name": "c6i.large",      "vcpus": 2,   "mem_gb": 4,    "gpu_count": 0, "gpu_model": "",      "price": 0.085},
    {"name": "c6i.xlarge",     "vcpus": 4,   "mem_gb": 8,    "gpu_count": 0, "gpu_model": "",      "price": 0.170},
    {"name": "c6i.2xlarge",    "vcpus": 8,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.340},
    {"name": "c6i.4xlarge",    "vcpus": 16,  "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.680},
    {"name": "c6i.8xlarge",    "vcpus": 32,  "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 1.360},
    {"name": "c6i.12xlarge",   "vcpus": 48,  "mem_gb": 96,   "gpu_count": 0, "gpu_model": "",      "price": 2.040},
    {"name": "c6i.16xlarge",   "vcpus": 64,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 2.720},
    {"name": "c6i.24xlarge",   "vcpus": 96,  "mem_gb": 192,  "gpu_count": 0, "gpu_model": "",      "price": 4.080},
    {"name": "c6i.32xlarge",   "vcpus": 128, "mem_gb": 256,  "gpu_count": 0, "gpu_model": "",      "price": 5.440},
    # General purpose
    {"name": "m6i.large",      "vcpus": 2,   "mem_gb": 8,    "gpu_count": 0, "gpu_model": "",      "price": 0.096},
    {"name": "m6i.xlarge",     "vcpus": 4,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.192},
    {"name": "m6i.2xlarge",    "vcpus": 8,   "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.384},
    {"name": "m6i.4xlarge",    "vcpus": 16,  "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 0.768},
    {"name": "m6i.8xlarge",    "vcpus": 32,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 1.536},
    {"name": "m6i.12xlarge",   "vcpus": 48,  "mem_gb": 192,  "gpu_count": 0, "gpu_model": "",      "price": 2.304},
    {"name": "m6i.16xlarge",   "vcpus": 64,  "mem_gb": 256,  "gpu_count": 0, "gpu_model": "",      "price": 3.072},
    {"name": "m6i.24xlarge",   "vcpus": 96,  "mem_gb": 384,  "gpu_count": 0, "gpu_model": "",      "price": 4.608},
    {"name": "m6i.32xlarge",   "vcpus": 128, "mem_gb": 512,  "gpu_count": 0, "gpu_model": "",      "price": 6.144},
    # Memory optimised
    {"name": "r7i.large",      "vcpus": 2,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.133},
    {"name": "r7i.xlarge",     "vcpus": 4,   "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.266},
    {"name": "r7i.2xlarge",    "vcpus": 8,   "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 0.532},
    {"name": "r7i.4xlarge",    "vcpus": 16,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 1.064},
    {"name": "r7i.8xlarge",    "vcpus": 32,  "mem_gb": 256,  "gpu_count": 0, "gpu_model": "",      "price": 2.128},
    {"name": "r7i.12xlarge",   "vcpus": 48,  "mem_gb": 384,  "gpu_count": 0, "gpu_model": "",      "price": 3.192},
    {"name": "r7i.16xlarge",   "vcpus": 64,  "mem_gb": 512,  "gpu_count": 0, "gpu_model": "",      "price": 4.256},
    {"name": "r7i.24xlarge",   "vcpus": 96,  "mem_gb": 768,  "gpu_count": 0, "gpu_model": "",      "price": 6.384},
    {"name": "r7i.48xlarge",   "vcpus": 192, "mem_gb": 1536, "gpu_count": 0, "gpu_model": "",      "price": 12.768},
]

# ---------------------------------------------------------------------------
# Azure instance catalog  (keep in sync with app.py)
# ---------------------------------------------------------------------------
AZURE_INSTANCES = [
    # H100
    {"name": "Standard_ND96isr_H100_v5",  "vcpus": 96,  "mem_gb": 900,  "gpu_count": 8, "gpu_model": "H100",  "price": 98.32},
    # A100
    {"name": "Standard_NC24ads_A100_v4",  "vcpus": 24,  "mem_gb": 220,  "gpu_count": 1, "gpu_model": "A100",  "price": 3.67},
    {"name": "Standard_NC48ads_A100_v4",  "vcpus": 48,  "mem_gb": 440,  "gpu_count": 2, "gpu_model": "A100",  "price": 7.35},
    {"name": "Standard_NC96ads_A100_v4",  "vcpus": 96,  "mem_gb": 880,  "gpu_count": 4, "gpu_model": "A100",  "price": 14.69},
    {"name": "Standard_ND96asr_v4",       "vcpus": 96,  "mem_gb": 900,  "gpu_count": 8, "gpu_model": "A100",  "price": 32.77},
    # V100
    {"name": "Standard_NC6s_v3",          "vcpus": 6,   "mem_gb": 112,  "gpu_count": 1, "gpu_model": "V100",  "price": 3.06},
    {"name": "Standard_NC12s_v3",         "vcpus": 12,  "mem_gb": 224,  "gpu_count": 2, "gpu_model": "V100",  "price": 6.12},
    {"name": "Standard_NC24s_v3",         "vcpus": 24,  "mem_gb": 448,  "gpu_count": 4, "gpu_model": "V100",  "price": 12.24},
    # A10G
    {"name": "Standard_NV6ads_A10_v5",    "vcpus": 6,   "mem_gb": 55,   "gpu_count": 1, "gpu_model": "A10G",  "price": 0.908},
    {"name": "Standard_NV12ads_A10_v5",   "vcpus": 12,  "mem_gb": 110,  "gpu_count": 1, "gpu_model": "A10G",  "price": 1.816},
    {"name": "Standard_NV18ads_A10_v5",   "vcpus": 18,  "mem_gb": 220,  "gpu_count": 1, "gpu_model": "A10G",  "price": 2.724},
    {"name": "Standard_NV36ads_A10_v5",   "vcpus": 36,  "mem_gb": 440,  "gpu_count": 2, "gpu_model": "A10G",  "price": 5.448},
    {"name": "Standard_NV72ads_A10_v5",   "vcpus": 72,  "mem_gb": 880,  "gpu_count": 4, "gpu_model": "A10G",  "price": 10.896},
    # T4
    {"name": "Standard_NC4as_T4_v3",      "vcpus": 4,   "mem_gb": 28,   "gpu_count": 1, "gpu_model": "T4",    "price": 0.526},
    {"name": "Standard_NC8as_T4_v3",      "vcpus": 8,   "mem_gb": 56,   "gpu_count": 1, "gpu_model": "T4",    "price": 0.752},
    {"name": "Standard_NC16as_T4_v3",     "vcpus": 16,  "mem_gb": 110,  "gpu_count": 1, "gpu_model": "T4",    "price": 1.204},
    {"name": "Standard_NC64as_T4_v3",     "vcpus": 64,  "mem_gb": 440,  "gpu_count": 4, "gpu_model": "T4",    "price": 4.352},
    # Compute optimised
    {"name": "Standard_F2s_v2",           "vcpus": 2,   "mem_gb": 4,    "gpu_count": 0, "gpu_model": "",      "price": 0.085},
    {"name": "Standard_F4s_v2",           "vcpus": 4,   "mem_gb": 8,    "gpu_count": 0, "gpu_model": "",      "price": 0.170},
    {"name": "Standard_F8s_v2",           "vcpus": 8,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.338},
    {"name": "Standard_F16s_v2",          "vcpus": 16,  "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.676},
    {"name": "Standard_F32s_v2",          "vcpus": 32,  "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 1.352},
    {"name": "Standard_F48s_v2",          "vcpus": 48,  "mem_gb": 96,   "gpu_count": 0, "gpu_model": "",      "price": 2.028},
    {"name": "Standard_F64s_v2",          "vcpus": 64,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 2.704},
    {"name": "Standard_F72s_v2",          "vcpus": 72,  "mem_gb": 144,  "gpu_count": 0, "gpu_model": "",      "price": 3.045},
    # General purpose
    {"name": "Standard_D2s_v5",           "vcpus": 2,   "mem_gb": 8,    "gpu_count": 0, "gpu_model": "",      "price": 0.096},
    {"name": "Standard_D4s_v5",           "vcpus": 4,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.192},
    {"name": "Standard_D8s_v5",           "vcpus": 8,   "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.384},
    {"name": "Standard_D16s_v5",          "vcpus": 16,  "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 0.768},
    {"name": "Standard_D32s_v5",          "vcpus": 32,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 1.536},
    {"name": "Standard_D48s_v5",          "vcpus": 48,  "mem_gb": 192,  "gpu_count": 0, "gpu_model": "",      "price": 2.304},
    {"name": "Standard_D64s_v5",          "vcpus": 64,  "mem_gb": 256,  "gpu_count": 0, "gpu_model": "",      "price": 3.072},
    {"name": "Standard_D96s_v5",          "vcpus": 96,  "mem_gb": 384,  "gpu_count": 0, "gpu_model": "",      "price": 4.608},
    # Memory optimised
    {"name": "Standard_E2s_v5",           "vcpus": 2,   "mem_gb": 16,   "gpu_count": 0, "gpu_model": "",      "price": 0.127},
    {"name": "Standard_E4s_v5",           "vcpus": 4,   "mem_gb": 32,   "gpu_count": 0, "gpu_model": "",      "price": 0.254},
    {"name": "Standard_E8s_v5",           "vcpus": 8,   "mem_gb": 64,   "gpu_count": 0, "gpu_model": "",      "price": 0.504},
    {"name": "Standard_E16s_v5",          "vcpus": 16,  "mem_gb": 128,  "gpu_count": 0, "gpu_model": "",      "price": 1.008},
    {"name": "Standard_E32s_v5",          "vcpus": 32,  "mem_gb": 256,  "gpu_count": 0, "gpu_model": "",      "price": 2.016},
    {"name": "Standard_E48s_v5",          "vcpus": 48,  "mem_gb": 384,  "gpu_count": 0, "gpu_model": "",      "price": 3.024},
    {"name": "Standard_E64s_v5",          "vcpus": 64,  "mem_gb": 512,  "gpu_count": 0, "gpu_model": "",      "price": 4.032},
    {"name": "Standard_E96s_v5",          "vcpus": 96,  "mem_gb": 672,  "gpu_count": 0, "gpu_model": "",      "price": 6.048},
]


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def parse_mem_mb(mem_str):
    s = mem_str.strip().upper()
    if not s or s in ("N/A", "0", "UNLIMITED"):
        return 0
    try:
        if s.endswith("T"):
            return int(float(s[:-1]) * 1024 * 1024)
        if s.endswith("G"):
            return int(float(s[:-1]) * 1024)
        if s.endswith("M"):
            return int(float(s[:-1]))
        if s.endswith("K"):
            return max(1, int(float(s[:-1]) / 1024))
        return int(s)
    except ValueError:
        return 0


def parse_sacct_mem_mb(mem_str):
    """Parse sacct ReqMem: strip trailing 'n' (per-node) or 'c' (per-cpu) suffix."""
    s = mem_str.strip().upper()
    if not s or s in ("0", "UNLIMITED", "N/A"):
        return 0
    if s.endswith("N") or s.endswith("C"):
        s = s[:-1]
    return parse_mem_mb(s)


def parse_tres_gpu(tres_str):
    """
    Parse GPU info from sacct ReqTRES field.
    Examples: 'billing=1,cpu=8,mem=32G,node=1,gres/gpu=2'  -> (2, '')
              'gres/gpu:a30=1'                               -> (1, 'a30')
    """
    if not tres_str:
        return 0, ""
    for part in tres_str.strip().lower().split(","):
        part = part.strip()
        if "gres/gpu" not in part:
            continue
        if "=" in part:
            key, val = part.rsplit("=", 1)
            try:
                count = int(val)
            except ValueError:
                count = 1
            model = key.split(":", 1)[1] if ":" in key else ""
            return count, model
    return 0, ""


def parse_sacct_timestamp(ts_str):
    """Convert sacct timestamp string (YYYY-MM-DDTHH:MM:SS) to Unix timestamp integer."""
    s = ts_str.strip()
    if not s or s.lower() in ("unknown", "none", ""):
        return 0
    try:
        return int(time_module.mktime(time_module.strptime(s, "%Y-%m-%dT%H:%M:%S")))
    except (ValueError, OverflowError):
        return 0


def parse_nodelist_first(nodelist_str):
    """
    Extract the first node name from a Slurm compressed NodeList string.
    Examples:
      'hpctpa3pc0001'          -> 'hpctpa3pc0001'
      'hpctpa3pc[0001-0005]'   -> 'hpctpa3pc0001'
      'node[01,03-05],gpu01'   -> 'node01'
    """
    import re
    s = nodelist_str.strip()
    if not s or s.lower() in ("n/a", "none", ""):
        return ""
    first = s.split(",")[0].strip()
    m = re.match(r"^([A-Za-z0-9._-]+)\[(\d+)", first)
    return (m.group(1) + m.group(2)) if m else first


# ---------------------------------------------------------------------------
# Instance matching  (keep in sync with app.py:find_best_instance)
# ---------------------------------------------------------------------------

def find_best_instance(catalog, cpus, mem_mb, gpu_count, gpu_model):
    mem_gb = mem_mb / 1024.0
    norm_gpu = GPU_MODEL_MAP.get(gpu_model.lower(), gpu_model.upper()) if gpu_model else ""

    if gpu_count > 0:
        c = [i for i in catalog
             if i["gpu_count"] >= gpu_count
             and (not norm_gpu or i["gpu_model"] == norm_gpu)
             and i["vcpus"] >= max(cpus, 1)
             and i["mem_gb"] >= mem_gb]
        if not c:
            c = [i for i in catalog
                 if i["gpu_count"] >= gpu_count
                 and (not norm_gpu or i["gpu_model"] == norm_gpu)
                 and i["vcpus"] >= max(cpus, 1)]
        if not c:
            c = [i for i in catalog
                 if i["gpu_count"] >= gpu_count and i["vcpus"] >= max(cpus, 1)]
        if not c:
            c = [i for i in catalog if i["gpu_count"] >= gpu_count]
        if c:
            return min(c, key=lambda x: x["price"])

    c = [i for i in catalog
         if i["gpu_count"] == 0 and i["vcpus"] >= max(cpus, 1) and i["mem_gb"] >= mem_gb]
    if not c:
        c = [i for i in catalog if i["gpu_count"] == 0 and i["vcpus"] >= max(cpus, 1)]
    if not c:
        c = [i for i in catalog if i["gpu_count"] == 0]
    if c:
        return min(c, key=lambda x: x["price"])
    return min(catalog, key=lambda x: x["price"])


# ---------------------------------------------------------------------------
# SQLite schema
# ---------------------------------------------------------------------------
SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS jobs (
    job_id        TEXT,
    cluster       TEXT,
    username      TEXT    NOT NULL,
    start_time    INTEGER,
    end_time      INTEGER,
    req_cpus      INTEGER DEFAULT 1,
    req_mem_mb    INTEGER DEFAULT 0,
    gpu_count     INTEGER DEFAULT 0,
    gpu_model     TEXT    DEFAULT '',
    time_limit_min INTEGER DEFAULT 0,
    elapsed_min   INTEGER DEFAULT 0,
    state         TEXT    DEFAULT '',
    aws_instance  TEXT    DEFAULT '',
    aws_total     REAL    DEFAULT 0.0,
    azure_instance TEXT   DEFAULT '',
    azure_total   REAL    DEFAULT 0.0,
    PRIMARY KEY (job_id, cluster)
);
CREATE INDEX IF NOT EXISTS idx_start   ON jobs(start_time);
CREATE INDEX IF NOT EXISTS idx_user    ON jobs(username);
CREATE INDEX IF NOT EXISTS idx_cluster ON jobs(cluster);
"""

INSERT_SQL_IGNORE  = "INSERT OR IGNORE  INTO jobs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
INSERT_SQL_REPLACE = "INSERT OR REPLACE INTO jobs VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"


def init_db(conn):
    for stmt in SCHEMA_SQL.strip().split(";"):
        stmt = stmt.strip()
        if stmt:
            conn.execute(stmt)
    conn.commit()


# ---------------------------------------------------------------------------
# Import logic
# ---------------------------------------------------------------------------

def import_csv(csv_path, db_path, default_gpu_model="", node_gpu_map=None, force_update=False):
    logger.info("Opening database: %s", db_path)
    if force_update:
        logger.info("--force-update: existing records will be REPLACED with recalculated costs.")
    if node_gpu_map:
        logger.info("Node GPU map loaded: %d nodes.", len(node_gpu_map))
    if default_gpu_model:
        logger.info("Default GPU model fallback: %s", default_gpu_model)
    INSERT_SQL = INSERT_SQL_REPLACE if force_update else INSERT_SQL_IGNORE
    os.makedirs(os.path.dirname(os.path.abspath(db_path)), exist_ok=True)
    conn = sqlite3.connect(db_path)
    init_db(conn)

    inserted = 0
    skipped = 0
    batch = []

    logger.info("Reading: %s", csv_path)
    with open(csv_path, "r") as fh:
        for line_num, line in enumerate(fh, 1):
            parts = line.rstrip("\n").split("|")
            # Support both legacy 12-column (no NodeList) and new 13-column format
            if len(parts) == 13:
                # New format: 12 sacct fields + ClusterName
                nodelist_str = parts[11].strip()
                cluster      = parts[12].strip() or "unknown"
            elif len(parts) == 12:
                # Legacy format: 11 sacct fields + ClusterName (no NodeList)
                nodelist_str = ""
                cluster      = parts[11].strip() or "unknown"
            else:
                skipped += 1
                continue

            job_id = parts[0].strip()
            if "." in job_id:
                skipped += 1
                continue  # Skip job steps (e.g. 12345.batch)

            username = parts[1].strip()
            start_ts = parse_sacct_timestamp(parts[3])
            if start_ts == 0:
                skipped += 1
                continue  # Skip jobs that never started

            try:
                req_cpus = int(parts[5].strip())
            except ValueError:
                req_cpus = 1

            try:
                elapsed_sec = int(parts[8].strip())
                elapsed_min = elapsed_sec // 60
            except ValueError:
                elapsed_min = 0

            try:
                time_limit_min = int(parts[9].strip())
            except ValueError:
                time_limit_min = 0

            gpu_count, gpu_model = parse_tres_gpu(parts[7])
            # GPU model resolution priority:
            #   1. Parsed directly from ReqTRES (most accurate)
            #   2. Node map lookup via NodeList (from scontrol show nodes)
            #   3. --default-gpu-model CLI fallback
            if gpu_count > 0 and not gpu_model:
                if nodelist_str and node_gpu_map:
                    first_node = parse_nodelist_first(nodelist_str)
                    gpu_model  = node_gpu_map.get(first_node, "")
                if not gpu_model and default_gpu_model:
                    gpu_model = default_gpu_model
            req_mem_mb = parse_sacct_mem_mb(parts[6])

            aws_inst   = find_best_instance(AWS_INSTANCES,   req_cpus, req_mem_mb, gpu_count, gpu_model)
            azure_inst = find_best_instance(AZURE_INSTANCES, req_cpus, req_mem_mb, gpu_count, gpu_model)

            # Use time_limit if available, otherwise fall back to elapsed
            time_hours = (time_limit_min or elapsed_min) / 60.0
            aws_total   = round(aws_inst["price"]   * time_hours, 4)
            azure_total = round(azure_inst["price"] * time_hours, 4)

            batch.append((
                job_id, cluster, username,
                start_ts, parse_sacct_timestamp(parts[4]),
                req_cpus, req_mem_mb,
                gpu_count, gpu_model,
                time_limit_min, elapsed_min,
                parts[10].strip(),
                aws_inst["name"],   aws_total,
                azure_inst["name"], azure_total,
            ))

            if len(batch) >= BATCH_SIZE:
                conn.executemany(INSERT_SQL, batch)
                conn.commit()
                inserted += len(batch)
                logger.info("  Inserted %d records (line %d)...", inserted, line_num)
                batch = []

    if batch:
        conn.executemany(INSERT_SQL, batch)
        conn.commit()
        inserted += len(batch)

    conn.close()
    logger.info("Import complete.  Inserted: %d  |  Skipped: %d", inserted, skipped)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Import sacct CSV dump into the Shovly historical SQLite database."
    )
    parser.add_argument(
        "csv_file", nargs="?", default="data/sacct_raw.csv",
        help="Path to the sacct pipe-delimited CSV (default: data/sacct_raw.csv)"
    )
    parser.add_argument(
        "--db", default="data/historical.db",
        help="Path to the SQLite database file (default: data/historical.db)"
    )
    parser.add_argument(
        "--default-gpu-model", default="", metavar="MODEL",
        help="GPU model fallback when ReqTRES and node map both lack model info "
             "(e.g. 'a30')."
    )
    parser.add_argument(
        "--node-gpu-map", default="", metavar="PATH",
        help="Path to node GPU map CSV generated by dump_history.sh "
             "(format: node_name|gpu_model, one per line). Used to resolve "
             "GPU model for jobs submitted without an explicit model in --gres."
    )
    parser.add_argument(
        "--force-update", action="store_true",
        help="Replace existing DB records instead of skipping them (INSERT OR REPLACE). "
             "Use this when re-importing after fixing GPU detection so that historical "
             "costs are recalculated with correct GPU instance pricing."
    )
    args = parser.parse_args()

    if not os.path.exists(args.csv_file):
        logger.error("CSV file not found: %s", args.csv_file)
        sys.exit(1)

    # Load node GPU map if provided
    node_gpu_map = {}
    if args.node_gpu_map:
        if not os.path.exists(args.node_gpu_map):
            logger.warning("Node GPU map file not found: %s — skipping.", args.node_gpu_map)
        else:
            with open(args.node_gpu_map, "r") as fh:
                for line in fh:
                    cols = line.strip().split("|")
                    if len(cols) == 2 and cols[0] and cols[1]:
                        node_gpu_map[cols[0].strip()] = cols[1].strip().lower()
            logger.info("Loaded node GPU map: %d nodes from %s.", len(node_gpu_map), args.node_gpu_map)

    import_csv(args.csv_file, args.db,
               default_gpu_model=args.default_gpu_model,
               node_gpu_map=node_gpu_map,
               force_update=args.force_update)


if __name__ == "__main__":
    main()
